import { ColumnDef } from "../types/register";

export const REGISTER_COLUMNS: ColumnDef[] = [
  {
    id: "invoice_number",
    label: "Invoice No",
    align: "left",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: true,
    width: "w-36",
  },
  {
    id: "invoice_date",
    label: "Invoice Date",
    align: "left",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: true,
    width: "w-32",
  },
  {
    id: "customer_name",
    label: "Customer Details",
    align: "left",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: true,
    width: "w-64",
  },
  {
    id: "total_taxable",
    label: "Taxable (₹)",
    align: "right",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: false,
    width: "w-36",
  },
  {
    id: "total_tax",
    label: "Tax (₹)",
    align: "right",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: false,
    width: "w-32",
  },
  {
    id: "total_value",
    label: "Total Value (₹)",
    align: "right",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: false,
    width: "w-40",
  },
  {
    id: "status",
    label: "Status",
    align: "center",
    sortable: true,
    exportable: true,
    defaultVisible: true,
    pinned: false,
    width: "w-32",
  },
  {
    id: "actions",
    label: "Actions",
    align: "center",
    sortable: false,
    exportable: false,
    defaultVisible: true,
    pinned: false,
    width: "w-24",
  },
];
