// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationLogRow = { id: bigint | null, timestamp: string, level: string, module: string, message: string, stack_trace: string | null, user_name: string, };