// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentRow = { id: bigint | null, record_type: string, record_id: string, file_name: string, file_path: string, mime_type: string, file_size: bigint, uploaded_at: string, };