// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditLogRow = { id: bigint | null, timestamp: string, user_action: string, table_name: string, record_id: string, old_value: string | null, new_value: string | null, };