// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupStatus = { last_backup_at: string | null, days_since_backup: bigint, is_backup_due: boolean, active_company_code: string, schema_version: number, };