// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Header metadata stored inside backup archives for verification
 */
export type BackupMetadata = { schema_version: number, app_version: string, timestamp: string, company_code: string, financial_year: string, db_file_name: string, db_size_bytes: bigint, };