// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BankRow = { id: bigint | null, bank_name: string, account_no: string, ifsc_code: string, branch: string, };