// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildConstants = { app_version: string, build_date: string, build_time: string, git_hash: string, git_branch: string, rust_version: string, target: string, profile: string, build_number: string, };