// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategoryCustomerBreakdownRow = { customer_id: bigint | null, customer_code: string, report_name: string, invoice_count: bigint, last_invoice_date: string | null, total_taxable: number, total_gst: number, total_value: number, };