// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategoryGrandTotals = { total_categories: number, total_customers: bigint, total_invoices: bigint, total_taxable: number, total_cgst: number, total_sgst: number, total_igst: number, grand_total_value: number, largest_category_name: string, largest_category_share: number, };