// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategorySalesRow = { category_id: bigint | null, category_name: string, customer_count: bigint, invoice_count: bigint, total_taxable: number, total_cgst: number, total_sgst: number, total_igst: number, total_value: number, };