// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditNoteItemUpdatePayload } from "./CreditNoteItemUpdatePayload";

export type CreditNoteUpdatePayload = { credit_note_number: string, new_credit_note_number: string | null, credit_note_date: string, remarks: string | null, reason: string | null, items: Array<CreditNoteItemUpdatePayload>, expected_revision_no: number, };