// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreditNoteCapabilities = { can_edit: boolean, reason_edit_disabled: string | null, can_delete: boolean, reason_delete_disabled: string | null, can_restore: boolean, reason_restore_disabled: string | null, can_submit: boolean, can_approve: boolean, can_print: boolean, };