// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogRow } from "./AuditLogRow";
import type { CreditNoteCapabilities } from "./CreditNoteCapabilities";
import type { CreditNoteHeader } from "./CreditNoteHeader";
import type { CreditNoteItemRow } from "./CreditNoteItemRow";
import type { CreditNoteTaxSummary } from "./CreditNoteTaxSummary";

export type CreditNoteDetails = { header: CreditNoteHeader, tax_summary: CreditNoteTaxSummary, items: Array<CreditNoteItemRow>, audit_timeline: Array<AuditLogRow>, capabilities: CreditNoteCapabilities, };