// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrencyRow = { currency_code: string, currency_name: string, symbol: string, };