// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomerImportIssue } from "./CustomerImportIssue";

export type CustomerImportPreview = { file_name: string, row_count: number, to_insert: number, to_update: number, errors: Array<CustomerImportIssue>, warnings: Array<CustomerImportIssue>, };