// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomerDebitNoteInvoiceMapRow } from "./CustomerDebitNoteInvoiceMapRow";

export type CustomerDebitNoteSimulation = { total_customers: number, total_invoices: number, total_parts: number, total_quantity: number, total_taxable: number, total_cgst: number, total_sgst: number, total_igst: number, total_cess: number, grand_total: number, currency: string, warnings: Array<string>, items: Array<CustomerDebitNoteInvoiceMapRow>, };