// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerPriceHistoryRow = { id: bigint | null, company_id: bigint, customer_id: bigint, part_number: string, old_price: number, new_price: number, difference: number, effective_date: string, revision_no: string | null, changed_by: string, changed_at: string, };