// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerImportIssue = { row_no: number, customer_code: string | null, severity: string, message: string, };