// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerRow = { id: bigint | null, customer_code: string, report_name: string, tally_customer_name: string | null, gstin: string | null, state_code: string | null, address: string | null, status: string, };