// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerTallyMappingRow = { id: bigint, sales_code: string, sales_name: string, tally_name: string | null, category_name: string | null, status: string, };