// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerCategoryRow = { id: bigint, name: string, description: string | null, created_at: string, };