// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerPartRow = { part_number: string, part_description: string | null, current_price: number, source: string, uom_code: string | null, hsn_code: string | null, };