// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerDebitNoteApprovalRow = { id: bigint | null, debit_note_id: bigint, step_order: number, step_name: string, user_id: string, user_name: string, action: string, remarks: string | null, created_at: string, };