// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomerImportIssue } from "./CustomerImportIssue";

export type CustomerImportResult = { batch_id: bigint, inserted: number, updated: number, skipped: number, errors: Array<CustomerImportIssue>, };