// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerPriceMasterRow = { id: bigint | null, company_id: bigint, customer_id: bigint, customer_name: string | null, part_number: string, part_description: string | null, current_price: number, effective_date: string, effective_to: string | null, updated_at: string, };