// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomerPriceRevisionItemRow = { id: bigint | null, revision_id: bigint, part_number: string, part_description: string | null, old_price: number, new_price: number, difference: number, price_source: string, remarks: string | null, };