// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebitNoteItemRow = { id: bigint | null, debit_note_number: string, invoice_number: string, part_code: string, quantity: number, rate_difference: number, assessable_difference: number, cgst_amount: number, sgst_amount: number, igst_amount: number, total_difference: number, };