// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticsInfo = { os_version: string, webview_version: string, tauri_version: string, rust_version: string, app_data_path: string, log_directory: string, };