// This file was generated by [ts-rs](https://github.com/Almetica/ts-rs). Do not edit this file manually.

export interface ExportResult {
  format: string;
  output_path: string;
  row_count: number;
  message: string;
}
