// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Export operation result returned to the frontend
 */
export type ExportResult = { format: string, output_path: string, row_count: number, message: string, };