// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FinancialYearRow = { id: bigint | null, label: string, start_date: string, end_date: string, is_active: number, is_locked: number, closed_at: string | null, };