// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GST summary breakdown by rate tier
 */
export type GstRateSummaryRow = { gst_rate: number, taxable_amount: number, cgst_amount: number, sgst_amount: number, igst_amount: number, total_tax: number, invoice_count: bigint, };