// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HsnMasterRow = { hsn_code: string, description: string | null, gst_rate: number, };