// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result summary of the historical HSN recovery process.
 */
export type HsnRecoveryReport = { total_candidates: number, matched: number, unmatched: number, ambiguous: number, repaired: number, details: Array<string>, };