// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportTemplateMappingRow = { id: bigint | null, template_id: bigint, excel_column_header: string, target_field_key: string, };