// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportTemplateRow = { id: bigint | null, template_name: string, source_type: string, is_active: number, };