// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvoiceSummary = { invoice_number: string, invoice_date: string, customer_code: string, customer_name: string, total_taxable: number, total_tax: number, total_value: number, status: string, };