// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvoiceItemUpdatePayload = { id: bigint | null, part_code: string, description: string | null, quantity: number, rate_pre_unit: number, cgst_rate: number, sgst_rate: number, igst_rate: number, };