// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvoiceItemUpdatePayload } from "./InvoiceItemUpdatePayload";

export type InvoiceUpdatePayload = { invoice_number: string, expected_version: number, customer_id: bigint, place_of_supply: string | null, reverse_charge: string | null, invoice_type: string | null, irn: string | null, irn_date: string | null, status: string, edit_reason: string, items: Array<InvoiceItemUpdatePayload>, };