export type InvoiceRow = {
  invoice_number: string;
  invoice_no_long: string | null;
  invoice_date: string;
  customer_id: number | bigint;
  financial_year_id: number | bigint;
  total_taxable: number;
  total_cgst: number;
  total_sgst: number;
  total_igst: number;
  total_cess: number;
  total_value: number;
  irn: string | null;
  irn_date: string | null;
  place_of_supply: string | null;
  reverse_charge: string | null;
  invoice_type: string | null;
  status: string;
  cancellation_date: string | null;
  import_batch_id: number | bigint | null;
  created_at: string;
  updated_at: string;
  version: number;
};