// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemRow = { part_code: string, part_name: string, hsn_code: string, uom_code: string, default_gst_rate: number, supplier_id: bigint | null, status: string, };