// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemPriceHistoryRow = { id: bigint | null, part_code: string, effective_date: string, old_price: number, new_price: number, supplier_id: bigint | null, reason: string | null, updated_by: string, };