// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result payload for database maintenance routines
 */
export type MaintenanceResult = { routine: string, status: string, details: string, duration_ms: bigint, };