// This file was generated by [ts-rs](https://github.com/Almetica/ts-rs). Do not edit this file manually.

export interface MonthlySalesRow {
  month_label: string;
  total_taxable: number;
  total_cgst: number;
  total_sgst: number;
  total_igst: number;
  total_value: number;
  invoice_count: number;
}
