// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top customer/supplier/item ranking for widgets
 */
export type RankingRow = { rank: number, code: string, name: string, total_value: number, total_qty: number, invoice_count: bigint, };