// This file was generated by [ts-rs](https://github.com/Almetica/ts-rs). Do not edit this file manually.

export interface RankingRow {
  rank: number;
  code: string;
  name: string;
  total_value: number;
  total_qty: number;
  invoice_count: number;
}
