// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportMetadata } from "./ReportMetadata";

export type ReportResult<R, G, F> = { metadata: ReportMetadata, filter: F, grand_totals: G, rows: Array<R>, };