// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportCapabilities } from "./ReportCapabilities";

export type ReportDefinition = { id: string, name: string, version: number, default_page_size: number, capabilities: ReportCapabilities, default_sort: string, };