// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportFilterCommon = { date_from: string | null, date_to: string | null, financial_year_id: bigint | null, invoice_statuses: Array<string> | null, include_cancelled: boolean | null, search_term: string | null, page: number | null, page_size: number | null, };