// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportCapabilities = { export_excel: boolean, export_csv: boolean, print: boolean, clipboard: boolean, charts: boolean, drilldown: boolean, };