// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomerPriceRevisionItemRow } from "./CustomerPriceRevisionItemRow";

export type RevisionExcelParseResult = { rows_read: number, valid_count: number, warning_count: number, error_count: number, items: Array<CustomerPriceRevisionItemRow>, validation_errors: Array<string>, };