// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupplierRow = { id: bigint | null, supplier_code: string, supplier_name: string, gstin: string | null, state_code: string | null, address: string | null, status: string, };