// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupplierPriceRevisionRow = { id: bigint | null, supplier_id: bigint, part_code: string, old_price: number, new_price: number, difference: number, effective_date: string, remarks: string | null, status: string, approved_at: string | null, created_at: string, };