// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidationErrorDetail = { row_no: number, invoice_no: string | null, field_name: string, error_type: string, actual_value: string, expected_value: string, };