// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VoucherSeriesRow = { id: bigint | null, voucher_type: string, financial_year_id: bigint, prefix: string | null, suffix: string | null, current_number: number, padding_length: number, };