import { ColumnDefinition } from "../../Table/types";
import { CustomerMasterRow } from "../../../types/bindings/CustomerMasterRow";

export const CUSTOMER_COLUMNS: ColumnDefinition<CustomerMasterRow>[] = [
  {
    id: "customer_code",
    title: "Customer Code",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.customer_code,
    filterAccessor: (r) => r.customer_code,
  },
  {
    id: "report_name",
    title: "Report Name",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.report_name,
    filterAccessor: (r) => r.report_name,
  },
  {
    id: "tally_name",
    title: "Tally Name",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.tally_name ?? "",
    filterAccessor: (r) => r.tally_name ?? "",
  },
  {
    id: "gstin",
    title: "GSTIN",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.gstin ?? "",
    filterAccessor: (r) => r.gstin ?? "",
  },
  {
    id: "location",
    title: "Location",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.location ?? "",
    filterAccessor: (r) => r.location ?? "",
  },
  {
    id: "category_name",
    title: "Category",
    sortable: true,
    exportable: true,
    searchable: false,
    defaultVisible: true,
    align: "left",
    sortAccessor: (r) => r.category_name ?? "",
    filterAccessor: (r) => r.category_name ?? "",
  },
  {
    id: "match_status",
    title: "Match Status",
    sortable: true,
    exportable: true,
    searchable: false,
    defaultVisible: true,
    align: "center",
    sortAccessor: (r) => r.match_status,
    filterAccessor: (r) => r.match_status,
  },
  {
    id: "status",
    title: "Approval Status",
    sortable: true,
    exportable: true,
    searchable: false,
    defaultVisible: false,
    align: "center",
    sortAccessor: (r) => r.status,
    filterAccessor: (r) => r.status,
  },
  {
    id: "legal_name",
    title: "Legal Name",
    sortable: true,
    exportable: true,
    searchable: true,
    defaultVisible: false,
    align: "left",
    sortAccessor: (r) => r.legal_name ?? "",
    filterAccessor: (r) => r.legal_name ?? "",
  },
  {
    id: "phone",
    title: "Phone",
    sortable: false,
    exportable: true,
    searchable: true,
    defaultVisible: false,
    align: "left",
    sortAccessor: (r) => r.phone ?? "",
    filterAccessor: (r) => r.phone ?? "",
  },
  {
    id: "email",
    title: "Email",
    sortable: false,
    exportable: true,
    searchable: true,
    defaultVisible: false,
    align: "left",
    sortAccessor: (r) => r.email ?? "",
    filterAccessor: (r) => r.email ?? "",
  },
  {
    id: "remarks",
    title: "Remarks",
    sortable: false,
    exportable: true,
    searchable: true,
    defaultVisible: false,
    align: "left",
    sortAccessor: (r) => r.remarks ?? "",
    filterAccessor: (r) => r.remarks ?? "",
  },
];
